export const availabilitySx = {
  telegramSection: {
    width: "100%",
    maxWidth: 980,
    mx: "auto",
    mt: 4,
    p: { xs: 2, md: 3 },
    borderRadius: 3,
    border: "1px solid var(--app-control-border)",
    bgcolor: "rgba(255,255,255,0.02)",
  },
  telegramHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 2,
    mb: 2.5,
  },
  telegramIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 2,
    display: "grid",
    placeItems: "center",
    bgcolor: "rgba(41, 182, 246, 0.12)",
    border: "1px solid rgba(41, 182, 246, 0.25)",
    flexShrink: 0,
  },
  telegramTitle: {
    color: "var(--app-text)",
    fontSize: 22,
    fontWeight: 600,
    lineHeight: 1.2,
  },
  telegramDescription: {
    color: "var(--app-text-muted)",
    mt: 0.5,
    fontSize: 14,
    lineHeight: 1.5,
  },
  telegramHelp: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    lineHeight: 1.5,
    mt: 1.5,
  },
  telegramForm: {
    display: "flex",
    flexDirection: "column",
    gap: 0.5,
  },
  telegramLinkedBox: {
    borderRadius: 2,
    border: "1px solid rgba(41, 182, 246, 0.25)",
    bgcolor: "rgba(41, 182, 246, 0.08)",
    px: 2,
    py: 2,
  },
  telegramPendingBox: {
    borderRadius: 2,
    border: "1px dashed rgba(255, 193, 7, 0.45)",
    bgcolor: "rgba(255, 193, 7, 0.08)",
    px: 2,
    py: 2,
  },
  disconnectButton: {
    borderColor: "var(--app-control-border)",
    color: "var(--app-text-muted)",
    textTransform: "none",
    "&:hover": {
      borderColor: "rgba(255,255,255,0.35)",
      bgcolor: "rgba(255,255,255,0.04)",
    },
  },
  pageMetaRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 1.5,
    mb: 2,
  },
  myStatusBox: {
    mb: 3,
    p: 2.5,
    borderRadius: 2,
    border: "1px solid var(--app-control-border)",
    bgcolor: "rgba(255,255,255,0.03)",
  },
  myStatusCompact: {
    mt: 2.5,
    pt: 2.5,
    borderTop: "1px solid var(--app-control-border)",
  },
  myStatusLabel: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    mb: 1,
  },
  myStatusRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 1.5,
  },
  myStatusMeta: {
    color: "var(--app-text-muted)",
    fontSize: 13,
  },
  myStatusHint: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    mt: 1,
  },
} as const;
