export const availabilitySx = {
  telegramSection: {
    width: "100%",
    maxWidth: 980,
    mx: "auto",
    mt: 4,
    p: { xs: 2, md: 3 },
    borderRadius: 3,
    border: "1px solid var(--app-control-border)",
    bgcolor: "rgba(255,255,255,0.02)",
  },
  telegramHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 2,
    mb: 2.5,
  },
  telegramIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 2,
    display: "grid",
    placeItems: "center",
    bgcolor: "rgba(41, 182, 246, 0.12)",
    border: "1px solid rgba(41, 182, 246, 0.25)",
    flexShrink: 0,
  },
  telegramTitle: {
    color: "var(--app-text)",
    fontSize: 22,
    fontWeight: 600,
    lineHeight: 1.2,
  },
  telegramDescription: {
    color: "var(--app-text-muted)",
    mt: 0.5,
    fontSize: 14,
    lineHeight: 1.5,
  },
  telegramHelp: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    lineHeight: 1.5,
    mt: 1.5,
  },
  telegramForm: {
    display: "flex",
    flexDirection: "column",
    gap: 0.5,
  },
  telegramLinkedBox: {
    borderRadius: 2,
    border: "1px solid rgba(41, 182, 246, 0.25)",
    bgcolor: "rgba(41, 182, 246, 0.08)",
    px: 2,
    py: 2,
  },
  telegramPendingBox: {
    borderRadius: 2,
    border: "1px dashed rgba(255, 193, 7, 0.45)",
    bgcolor: "rgba(255, 193, 7, 0.08)",
    px: 2,
    py: 2,
  },
  disconnectButton: {
    borderColor: "var(--app-control-border)",
    color: "var(--app-text-muted)",
    textTransform: "none",
    "&:hover": {
      borderColor: "rgba(255,255,255,0.35)",
      bgcolor: "rgba(255,255,255,0.04)",
    },
  },
  pageMetaRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 1.5,
    mb: 2,
  },
  myStatusBox: {
    mb: 3,
    p: 2.5,
    borderRadius: 2,
    border: "1px solid var(--app-control-border)",
    bgcolor: "rgba(255,255,255,0.03)",
  },
  myStatusCompact: {
    mt: 2.5,
    pt: 2.5,
    borderTop: "1px solid var(--app-control-border)",
  },
  myStatusLabel: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    mb: 1,
  },
  myStatusRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 1.5,
  },
  myStatusMeta: {
    color: "var(--app-text-muted)",
    fontSize: 13,
  },
  myStatusHint: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    mt: 1,
  },
  assistantPanel: {
    mb: 3,
    p: 2.5,
    borderRadius: 2,
    border: "1px solid var(--app-control-border)",
    bgcolor: "rgba(255,255,255,0.03)",
  },
  assistantHeader: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    mb: 0.5,
    color: "var(--app-text)",
  },
  assistantTitle: {
    fontSize: 18,
    fontWeight: 600,
  },
  assistantHint: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    mb: 1.5,
  },
  assistantSuggestions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 1,
    mb: 2,
  },
  assistantSuggestionButton: {
    textTransform: "none",
    borderColor: "var(--app-control-border)",
    color: "var(--app-text-muted)",
  },
  assistantMessages: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    minHeight: 120,
    maxHeight: 280,
    overflowY: "auto",
    mb: 2,
    pr: 0.5,
  },
  assistantEmpty: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    fontStyle: "italic",
  },
  assistantUserMessage: {
    alignSelf: "flex-end",
    maxWidth: "85%",
    px: 1.5,
    py: 1,
    borderRadius: 2,
    bgcolor: "rgba(41, 182, 246, 0.15)",
    border: "1px solid rgba(41, 182, 246, 0.25)",
  },
  assistantBotMessage: {
    alignSelf: "flex-start",
    maxWidth: "90%",
    px: 1.5,
    py: 1,
    borderRadius: 2,
    bgcolor: "rgba(255,255,255,0.04)",
    border: "1px solid var(--app-control-border)",
  },
  assistantMessageText: {
    color: "var(--app-text)",
    fontSize: 14,
    whiteSpace: "pre-wrap",
  },
  assistantSource: {
    color: "var(--app-text-muted)",
    fontSize: 11,
    mt: 0.5,
  },
  assistantError: {
    color: "#ffb4b4",
    fontSize: 13,
    mb: 1,
  },
  assistantForm: {
    display: "flex",
    gap: 1,
    alignItems: "flex-start",
  },
} as const;
